assassins-insta-kill-speedrunner: false
compass-tracking: true
compass-give: true
compass-particle: false
compass-particle-in-nether: false
compass-random-different-worlds: false
freeze-assassin-when-seen: false
